# Nome da Actions:  
name: Snake Game

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"

  # Permite executar na lista de Actions (utilizado para testes de build).
  workflow_dispatch:

# Regras
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checks repo under $GITHUB_WORKSPACE, para que o job possa acessar o repositório.
      - uses: actions/checkout@v2

      # Repositório que será utilizado para gerar os arquivos.
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: edsonrdl
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Verifica o status do repositório (opcional para debug).
      - run: git status

      # Para realizar atualizações no repositório.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publica os arquivos no branch `output`.
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # Branch de saída mencionado acima.
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
